name: Setup Git

runs:
  using: composite
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    
    - name: Git fetch all
      shell: bash
      run: git fetch --all