
# template for src/<userscript-name>/userscript.yml

owowed:id: untitled-userscript
name: ${{ owowed:id }}
description: https://github.com/owowed/owowed-userscripts
version: 1.0.0
namespace: owowed.moe
author: owowed <island@owowed.moe>
homepage: https://github.com/owowed/owowed-userscripts
supportURL: https://github.com/owowed/owowed-userscripts/issues
match:
  - "*://example.com/"
require:
  - https://github.com/owowed/oxi/raw/dist/oxi.umd.js
grant: none
license: LGPL-3.0
updateURL: https://github.com/owowed/owowed-userscripts/raw/dist/${{ owowed:id }}.user.js
downloadURL: https://github.com/owowed/owowed-userscripts/raw/dist/${{ owowed:id }}.user.js