name: Main Action

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      - name: Draft release
        id: release-draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-package:
    uses: ./.github/workflows/update-package.yml
    needs: release-draft
    permissions:
      contents: write
    with:
      tag_name: ${{ needs.release-draft.outputs.tag_name }}

  