name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: {}

jobs:
  release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      - name: Draft release
        id: release-draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-package:
    uses: ./.github/workflows/update-package.yml
    needs: release-draft
    permissions:
      contents: write
    with:
      tag_name: ${{ needs.release-draft.outputs.tag_name }}
  
  post-release-draft:
    needs: update-package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release-draft.outputs.tag_name }}
    steps:
      - name: Draft release
        id: release-draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: refs/heads/package

  